title: Tua on GitHub
suffix: 
description: Exploring space

name: Tua on Github
url: "https://clumdee.github.io"
baseurl: ""
base_canonical: "https://clumdee.github.io"
permalink: 

social:
   email: "chatdanai.l@gmail.com"
   github: https://github.com/clumdee
   linkedin: https://www.linkedin.com/in/chatdanai-lumdee/

google_analytics: "G-NG12M3TDGG"